name: deploy
on: [push, workflow_dispatch]
jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: build the docker image
        run: npm run build
      - name: Upload docker image artifact
        uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with:
          image: "codingwitherik995/app:1.0"

  deploy:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3
      - name: Download the docker image artifact
        uses: ishworkh/container-image-artifact-download@v1.0.0
        with:
          image: "codingwitherik995/app:1.0"
      - name: login to docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: push image to docker hub
        run: docker push codingwitherik995/app:1.0
